### ISSUE TITLE
Black screen on HTML5 Method

### ISSUE THREAD

**Issue by dirtysockgames** [shdwcat/YUI#59] opened 2023-01-03 09:01 UTC
Was curious if this was supported platform or not :)

It appears to have the error "undefined" for Inventory & welcome_screen rooms.

Best!,
DirtySock

**Comment by shdwcat** [comment] 2023-01-03 21:28
Unfortunately html5 is not currently supported because YUI relies on datafiles which html5 does not seem to allow. I'll note this on the main readme. It may be possible to fix in the future but I don't have an HTML5 license so I can't try to fix it yet.

**Comment by shdwcat** [comment] 2023-03-11 22:04
Closing as duplicate of #28

**Closed by shdwcat** 2023-03-11 22:04 UTC
Labels: bug
